{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reader-lab.fullname" . }}
  labels:
    {{- include "reader-lab.labels" (dict "root" . "extra" .Values.extraLabels) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "reader-lab.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
